apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Tomamos toda la plantilla de la carpeta base
resources:
  - ../../base

# Automáticamente a todos los recursos les agregará este prefijo (ej. dev-importa-acreditados-sis)
namePrefix: dev-

# Automáticamente desplegará todo en el namespace "dev" en lugar del default
namespace: dev

# Aquí aplicamos un "parche" para cambiar la URL solo para desarrollo
patches:
  - path: patch-ingress.yaml
